## Tensors Examples

In [3]:
import torch

a = torch.tensor(1.)
print(a)

tensor(1.)


In [2]:
b = 1.
print(b)

1.0


In [3]:
print(a.shape)

torch.Size([])


## Rank 1 Tensor, Vectors

In [4]:
b = [1., 2., 3.]
print(b)

[1.0, 2.0, 3.0]


In [5]:
a = torch.tensor([1., 2., 3.])
print(a)

tensor([1., 2., 3.])


In [6]:
print(a.shape)

torch.Size([3])


In [7]:
print(a.size)

<built-in method size of Tensor object at 0x1345b4730>


## Rank 2 Tensor, Matrix

In [8]:
a = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
print(a)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
print(a.shape)

torch.Size([2, 3])


In [10]:
a.shape

torch.Size([2, 3])

In [11]:
a.dim

<function Tensor.dim>

## 3D Tensor

In [12]:
a = torch.tensor([[[1., 2., 3.],
                   [4., 5., 6.]],
                  [[7., 8., 9.],
                   [10., 11., 12.]]])
print(a)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


In [13]:
a.shape

torch.Size([2, 2, 3])

## 4D Tensor

In [14]:
a = torch.tensor([[[[1., 2., 3.],
                   [4., 5., 6.]],
                  [[7., 8., 9.],
                   [10., 11., 12.]]],
                  [[[13., 14., 15.],
                   [16., 17., 28.]],
                  [[19., 20., 21.],
                   [22., 23., 24.]]]])
print(a)

tensor([[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],

         [[ 7.,  8.,  9.],
          [10., 11., 12.]]],


        [[[13., 14., 15.],
          [16., 17., 28.]],

         [[19., 20., 21.],
          [22., 23., 24.]]]])


In [ ]:
a.shape

# Useful Tensor Functions

## 1) Creating a tensor

In [15]:
t = torch.tensor([[1., 2., 3.], [4., 5., 6.]])

## 2) Check the shape

In [16]:
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [17]:
print(t.shape)

torch.Size([2, 3])


## 3) Check the rank, or number of dimensions

In [18]:
print(t.ndim)

2


## 4) Check the data type

In [19]:
print(t.dtype)

torch.float32


In [20]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]]) 

In [21]:
print(a.dtype)

torch.int64


## 5) Convert numpy array to tensor

In [22]:
import numpy as np
np_array = np.array([1., 2., 3.])
t1 = torch.from_numpy(np_array)
t2 = torch.tensor(np_array)
# t and np_array share the same memory
print(np_array)
print(t1)
print(t2)

[1. 2. 3.]
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float64)


In [23]:
t1[2] = 10.

In [24]:
print(t1)

tensor([ 1.,  2., 10.], dtype=torch.float64)


In [25]:
print(np_array)

[ 1.  2. 10.]


In [26]:
print(t2)

tensor([1., 2., 3.], dtype=torch.float64)


In [27]:
t2[0] = 20.

In [28]:
print(t2)

tensor([20.,  2.,  3.], dtype=torch.float64)


In [29]:
print(t1)
print(np_array)

tensor([ 1.,  2., 10.], dtype=torch.float64)
[ 1.  2. 10.]


## 6) Change data type

In [30]:
print(t1.dtype)

torch.float64


In [31]:
t1 = t1.to(torch.float32)

In [32]:
print(t1.dtype)

torch.float32


## 7) Check the device type

In [33]:
t1.device

device(type='cpu')

In [34]:
torch.cuda.is_available()

False

## 8) Change tensor shape

In [35]:
a = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
print(a)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [36]:
print(a.view(3,2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [37]:
print(a.view(-1,2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [38]:
print(a.view(3,-1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


## 9) Transpose a tensor

In [39]:
a = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
print(a)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [40]:
print(a.T)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [41]:
b = torch.tensor([[[1., 2., 3.],
                  [4., 5., 6.]],
                  [[7., 8., 9.],
                   [10., 11., 12.]]])
print(b)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


In [42]:
print(b.mT)

tensor([[[ 1.,  4.],
         [ 2.,  5.],
         [ 3.,  6.]],

        [[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]])


## 10) Multiplying matrices

In [4]:
a = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
b = torch.tensor([[2., 3., 4.],
                  [5., 6., 7.],
                  [8., 9., 10]])

In [44]:
a.matmul(b.T)

tensor([[ 20.,  38.,  56.],
        [ 47.,  92., 137.]])

In [45]:
import torch
a = torch.tensor([[1.,2.], [3.,4.]])
b = torch.tensor([10.,20.])

In [46]:
a

tensor([[1., 2.],
        [3., 4.]])

In [47]:
b

tensor([10., 20.])

In [48]:
a+b

tensor([[11., 22.],
        [13., 24.]])